"""Added water saving data collection columns

Revision ID: 0c66627502a5
Revises: 82b33370ddc2
Create Date: 2022-05-26 18:54:20.045154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c66627502a5'
down_revision = '82b33370ddc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_conservation', sa.Column('no_of_taps', sa.Integer(), nullable=False))
    op.add_column('water_conservation', sa.Column('no_of_leaky_taps', sa.Integer(), nullable=False))
    op.add_column('water_conservation', sa.Column('delta_leakage_per_min', sa.Integer(), nullable=False))
    op.add_column('water_conservation', sa.Column('avg_flow_rate', sa.Integer(), nullable=False))
    op.add_column('water_conservation', sa.Column('time_to_wash_vessel', sa.Integer(), nullable=False))
    op.add_column('water_conservation', sa.Column('saved_using_rwh', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_conservation', 'saved_using_rwh')
    op.drop_column('water_conservation', 'time_to_wash_vessel')
    op.drop_column('water_conservation', 'avg_flow_rate')
    op.drop_column('water_conservation', 'delta_leakage_per_min')
    op.drop_column('water_conservation', 'no_of_leaky_taps')
    op.drop_column('water_conservation', 'no_of_taps')
    # ### end Alembic commands ###
