"""Added amsdcapp model

Revision ID: ac3353931d5d
Revises: cfaa4f49a279
Create Date: 2022-10-05 07:45:10.326952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3353931d5d'
down_revision = 'cfaa4f49a279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amsdc_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniqname', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('released', sa.DateTime(), nullable=True),
    sa.Column('lastupdated', sa.DateTime(), nullable=True),
    sa.Column('latestver', sa.String(length=64), nullable=True),
    sa.Column('license', sa.String(length=30), nullable=False),
    sa.Column('programming_lang', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('copyright', sa.String(length=64), nullable=True),
    sa.Column('repository', sa.String(length=224), nullable=True),
    sa.Column('installer', sa.String(length=224), nullable=True),
    sa.Column('shortdesc', sa.String(length=500), nullable=True),
    sa.Column('longdesc', sa.TEXT(length=2400000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amsdc_app_uniqname'), 'amsdc_app', ['uniqname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amsdc_app_uniqname'), table_name='amsdc_app')
    op.drop_table('amsdc_app')
    # ### end Alembic commands ###
